### ISSUE TITLE
HIP 125: Temporary Anti-Gaming Measures For Boosted Hexes

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#1022]
# HIP 125: Temporary Anti-Gaming Measures For Boosted Hexes

- Author(s): [jhella](https://github.com/jhella) & [jaym2518](https://github.com/jaym2518)
- Start Date: 2024-05-20
- Category: Economic, Technical
- Original HIP PR: [#1017](https://github.com/helium/HIP/pull/1017)
- Tracking Issue: [#1022](https://github.com/helium/HIP/issues/1022)
- Vote Requirements: veMOBILE Holders

---

## Summary

This proposal outlines measures to invalidate boosted hex rewards for mobile hotspots that engage in malicious activity to earn boosted hex rewards on the MOBILE network.

## Rendered View

https://github.com/helium/HIP/blob/main/0125-temporary-anti-gaming-measures-for-boosted-hexes.md

**Comment by waveform06** [comment]
HIP 125 was approved by the community on 20th June 2024 with a passing rate of 90.81%
https://heliumvote.com/mobile/proposals/2z9WenqeZvdCuPEDJBKn4dDPequj99SURYYZNUtooyfN
