### ISSUE TITLE
Comprimised 

### ISSUE THREAD

**Issue by mathaipreetha** [helium/HIP#1085]
How to change all 4 hotspot to new wallet. Please help!
Wallet address  H1g4FxdyF96Sp1uyJSCFWFezmqW9LeUSrVGPWwkvqByG

**Comment by waveform06** [comment]
@mathaipreetha 
The place to ask questions is in the https://discord.com/invite/helium
#iot-questions-and-answers for IOT
#5g-cbrs for CBRS
#5g-wifi for WiFi
