### ISSUE TITLE
HIP 139

### ISSUE THREAD

**Issue by hardparker** [helium/HIP#1122]
#HIP 139 - Solidifying previous tokenomics in perpetuity. HNT, IOT, MOBILE and any other previous or subsequent issuances of token for helium network, nova labs and any extant supporters should permanently instantiate all previous tokenomic issuances, whitepapers, measures and algorithms to preserve those and any other subsequently issued tokens in perpetuity. Internal exchange treasuries for all tokens should be stocked to serve full issuance of any liquidity pools or other types of token debts to 100% of issuance value, with fully internal exchangeability with zero slippage and zero or nominal fee, preferably of the "free gas" variety, absorbed internally. 

Reasoning: The various tokens have been issued to supporters who have ascribed due to the circumstances of the particulars of the technology, tokenomics and economics of the time. The tokenomics and economics of LoRa versus consumer mobile are radically disparate. Moving these into HNT via HIP 138 eradicates all previous logic, which is unreasonable post-factually. HIP 139 will preserve all previous tokenomics. Any subsequent transcription of tokenomics must honor previous whitepaper tokenomics as well as relative subscriber issuances and overall market viability posthumously.

**Comment by capjbadger007** [comment]
AKA You can never change the system with a HIP.

...NO
