### ISSUE TITLE
HIP27: Support CBRS 5G on the Helium network

### ISSUE THREAD

**Issue by jamiew** [helium/HIP#134]
**Author(s):** @zer0tweets (Boris Renski, FreedomFi)
**Initial PR:** #133 
**Start Date:** 2020-02-23
**Category:** Technical, Economic

**Rendered view:**

https://github.com/helium/HIP/blob/master/0027-cbrs-5g-support.md

**Summary:**

This proposal suggests a technical and economic mechanisms to support higher new wireless protocols on Helium network, starting with LTE and 5G in CBRS spectrum band

**Comment by jdgemm** [comment]
super exciting, unless I'm misunderstanding are there concerns about the pricing proposal costing 5x that of comcast? 

"Comcast charges $10 for each $50GB"

"we initially set the price of passing 1GB of CBRS data through Helium network at $1 per GB"

**Comment by zer0tweets** [comment]
$10 per 50GB is retail price for Comcast fiber/cable backhaul, not for cellular service; we just put that data point for reference to see what backhaul costs could look like and make sure they won't be more than cost Helium price for cellular

**Comment by 3gedge** [comment]
It would amazing to achieve this!!!!!! I can help with the product management / research side (I know you have your team but I'd be happy to share my knowledge).

**Comment by jamiew** [comment]
On behalf of the @dewi-alliance I am pleased to memorialize community support for this proposal, as evidenced by supportive comments here on GitHub, on Discord, 
[popular support in informal polling](https://user-images.githubusercontent.com/1903/115044580-a466f200-9ea3-11eb-8b54-db3af34e5cf7.png), and support during the most recent community call. I'll be submitting a separate PR to mark this proposal `approved.` 

I believe FreedomFi is already hard at work on the code necessary to actually impement this concept. At that point the HIP would actually become real, and the code changes go through further review, testing, and deployment.

**Comment by puppetsock** [comment]
It would be great to get some clarity on the requirements for LTE EPC's for use with this HIP. I'm aware that FreedomFI is planning on producing a product around this proposal, but can other companies or individuals also participate?

**Comment by sysfu** [comment]
I'm interested in learning how sharing consumer grade Internet connection bandwidth via 5G Helium hotspots does not create legal problems by violating the Terms of Service. The vast majority of consumer grade Internet broadband products specifically prohibit the customer from 'reselling' the service.
