### ISSUE TITLE
Validator HNT stake threshold is prohibitive

### ISSUE THREAD

**Issue by cstnn** [helium/HIP#161]
For a decentralized blockchain the number of validators seems pretty low and the stake amount is pretty prohibitive creating a very high barrier of entry.
The 10k HNT are equivalent of ~$150k and is a huge limit for an "average" (**1**) person to start validator node.
At the current stake level this means that very early adopters or people with this money to spare would be able to even think about running a validator. 
Having a low number of validators is also risky for the blockchain even if the current number of gateways is relatively low now... it will explode in H2 this year.

I agree that the barrier of entry should not be very low either but I would say something in the range of ~$5k-$10k (equivalent of HTN) would be a much better starting staking threshold.

(**1**) By "average" person I mean someone who is in the Helium network already, has some HTN or can buy some and has technical skills to setup the validator node.

**Comment by jamiew** [comment]
@cstnn could you post this as a comment on #111 instead? Thanks
