### ISSUE TITLE
How to govern a  decentralized network

### ISSUE THREAD

**Issue by GP-Colorado** [helium/HIP#163]
The Decentralized Wireless Alliance (dewi.org) advertises itself as "the Foundation arm of the Helium block-chain and its global community". It is a not-for-profit organization established and run by early investors of the for-profit Helium Systems Inc. with the declared purpose of "supporting the Helium community worldwide, we are responsible for fostering research, development, and innovation at the intersection of radio hardware, sensors and manufacturing, blockchain, and peer-to-peer systems". 

Not-for-profit implies neither that an organization is, nor is not, dedicated to advocating in an unbiased way the interests of all stakeholders or of the public-at-large. 

DeWi is seen as a benevolent non-biased entity.  However, while the current directors and dues-paying members may be benevolent, with interests aligned with those of all in the community, it is folly to _assume_ that this is, and always will be, true.

**There is nothing wrong with the founders having a trade organization**. However, I suggest that it should either hold no arbitrary authority regarding Helium Improvement Proposals (HIPs) OR it should be fully transparent to the community regarding all factors which might reasonably be perceived as potentially leading to conflicts of interest.  This would include, for all directors and managerial employees/consultants:
1)	Full legal names
2)	Relationships, including employment with,  and beneficial holdings of stock and other securities of, Helium Systems Inc. and entities that produce or supply relevant products and services.
3)	Beneficial holdings of Helium Security Tokens (HST) and Helium Network Tokens (HNT).

Additionally, the terms by which the board of directors and voting membership in the organization is determined should be clearly displayed on its website. 

Ideally, I believe that approval and implementation of HIPS and all adjustment of chain variables and firmware code should be controlled by a well-defined and representative organization.  The current system of holding a vote by a few dozen folks who know to keep an eye open and regularly check the proposals on Discord could result in decisions contrary to the interests of many or most being implemented.

I expect that some, upon reading the above might be tempted to say – So you don’t like the status quo; where is your fleshed-out proposal for the future?  Why are you bringing this up here without one?  

To which I would reply that I believe that this is a topic worthy of discussion and that I have learned that to raise such issues for discussion in Discord is not, by some, taken “seriously”.  While I do not flatter myself to know how best the matter should be addressed, nor all of the factors that should be considered, I am hopeful that a good discussion will result in a proposal with wide acceptance.  

If it turns out that the current system is widely viewed as the best that option available, I'll be fine with that.  I really don't know.

**Comment by jamiew** [comment]
@GP-Colorado I welcome any critique of our collective governance, and as a board member of DeWi and the de-facto manager of the current HIP process, I would be happy to discuss some of your ideas. Unfortunately this repository is not an open discussion forum. I'd invite you to put this into a proposal following the template and process outlined in [HIP7](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md), which was itself a critique (with suggested solutions) for Helium's governance at the time.

**Comment by GP-Colorado** [comment]
I attempted to open a related topic for discussion in Discord #hip-open-discussion channel and heard that it was not the appropriate place. So, I came to the repository to open the discussion.  But apparently, this is not the appropriate place either.  I did not want to take the step of making a full-fledged HIP until I had raised my concerns and gotten the thoughts of others in a collaborative process, as I don't believe that I should escalate to that unless I am confident that my observations are of concern to others.  

I'll be happy to chat with you and others about the topic. So please tell me, where would be the appropriate venue for me to bring this up to solicit more information, perspectives, and ideas for improvements?
