### ISSUE TITLE
Eden Litespot

### ISSUE THREAD

**Issue by TyeG1250** [helium/HIP#188]
Eden Litespot
Summary
My name is Tyrell Gerald. I plan to build lite helium hotspots mainly for the Canadian market at a reduced price and much faster and more reliable delivery. I understand the importance of credibility and experience and I know that all the other applications will be from big companies with years of formal experience I may not have all the experience as the other but I do have the drive and determination to provide a excellent product and to help grow the helium network and ensure that the Canadian market can play a big role in that. I don’t think that it’s right for the people who may have learned about helium a bit too late to not have the opportunity to be apart of something this spectacular and therefore If given the opportunity I will do everything in my power to make this a reality and help spread the word that is helium. Thank you in advance for the consideration and please let me know what additional information is needed 

Company Information
Business network home automation data systems have been around computers and all electronics for years. I have built multiple computers and have put together functioning home automation systems.What brought me to the helium network is the idea of creating a more reliable coverage network. And rewarding its users for providing a service 

Product Information
So just like all the other units on the market I will be using a sbc like the  Raspberry Pi and then will be adapting the Sx1302 LoRa card which will provide 10 programmable parallel demodulation paths, an 8 x 8 channel LoRa packet detector, 8 x SF5-SF12 LoRa demodulators and 8 x SF5-SF10 LoRa demodulators. It is capable of detecting an uninterrupted combination of packets at 8 different spreading factors and 10 channels with continuous demodulation of up to 16 packets. For software I will adapt everything to run on the helium app and We will provide ota updates. that way it’s directly on the network and we don’t have to worry about security risks my goal would be to produce as many units as required with the order numbers I would be able to have the units assembled and shipped within 3-5 days of receiving the order my goal price point would be 450-500$ cad until we can get the price for the components down and at that point 300$ a unit. I will provide prototype photos and videos at a later date as I would like to see if I have a chance before starting to build it 

Customer Service
I will provide email customer support and have a solid amount of people ready to get to the customers and resolve their issues I have years of experience working in customer service and technical support for companies such as Telus bell mobility ect. for repairs and replacements I will have the customer send the unit back in to the headquarters inspect and repair and send them back out until it will be possible to have a location in every province where they will be able to bring the units in person and have them repaired on site or replaced if needed each unit will have a 1 year replacement warranty which will cover any hardware issue 

Hardware security 
The swarm keys will be stored on a secured EMMC storage card 

Manufacturing Information
Have built data centres and multiple electronic systems from computers to smart home panels phone systems intercoms ect. I have personally created similar units years ago before helium was a thing and am very familiar with the technology. 

Proof of Identity
To be provided in private message .

Budget & Capital
The plan is to fund the initial development personally and I am confident that the profits and pre orders will be able to more then cover any expense I will also plan to have a large amount of units already in stock and ready to be shipped out upon order I will ensure to update the availability of the units accordingly and will only allow pre orders of up to a week delay to avoid having customers pay for a product and not receive it for months 

Risks & Challenges
The only challenges I see would be the shipping of the units but to address this issue I plan to use multiple shipping companies and providing local shipping service 

Other information
Desired Discord support channel name -
Twitter profile -Eden.Litespot
Facebook profile --Eden.Litespot
Other social profiles --Eden.Litespot
Website --EdenLitespot.io or .com or .ca
Payment methods available - debit credit crypto
Regions covered / shipped to - Canada 

Your Name
Tyrell Gerald, upon approval I plan to structure a formal company and I will be the ceo.

**Comment by Sophi** [comment]
Hi Tyrell, we emailed you instructions on how to get this application into the right place.

**Comment by TyeG1250** [comment]
Hi 

Thank you so much I was able to put the application in the list I’m almost certain there’s going to be some information  missing or that I would need to elaborate on and the KYC really looking forward to working with you. All to get this application approved 

Thank you again 

Regards 

Tyrell

**Comment by Sophi** [comment]
Thanks for your submission. The manufacturing review committee will be in touch next week.
