### ISSUE TITLE
HIP XX - Validators multi-wallet feature

### ISSUE THREAD

**Issue by rootvanished** [helium/HIP#202]
I would like to propose that the Validators support somewhere between 5-10 wallets to avoid that only a limited number of people that is holding 10k+ HNT can be able to contribute with a validator. 

The staking wallets would retain a % of the 10K that are demanded to run a validator and then it would split the earned HNT across the wallets that are part of this validator.

The current design is benefiting strictly major HNT holders and is not providing an opportunity for smaller holders to have a staking chance within the Helium Project,

**Comment by kellybyrd** [comment]
See https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md for the process and how to propose and actual HIP. This isn't an actual HIP. It's just an issue filed.  It is likely to get closed.

See previous HIPs for examples of what is expected in a HIP that gets taken to a vote.
