### ISSUE TITLE
Invalid witnesses after fresh install on new miner with 8dbi antenna. 

### ISSUE THREAD

**Issue by PiParmy** [helium/HIP#217]
Hello, I am having an issue where my newly installed hotspot is getting invalid witnessing of another unit. The odd part is that unit is witnessing me back just fine. I am wondering what can cause this? 

Is it my antenna gain is too high? Is my antenna moving in the wind making it seem like it's moving or something I am very confused about how the blockchain can just decide the miner I paid for is not valid or not sending valid signals? I opened the box, programed it and plugged in the antenna, and left it. There are no settings to change so how is this even a rule? Maybe the antenna is overpowered or greatly unpowered (higher or lower dbi than advertised)?  

Anyone have a clue or can tell me what is going on/causing this? Anything I can try? Do I change antennas? 

RSSI        | SNR      | Distance | Data rate
-105dBm | 10.50dB | 1.5 km    | SF9BW125

Please help if you can. This is my only witness and he will only witness my beacons I cannot witness his back. I am so confused and would greatly appreciate any tips that may help. 

Thank you for your time today.

**Comment by PiParmy** [comment]
I noticed when I send a beacon and his witnesses it, it shows 1.3km but when he beacons and I witness his, it shows 1.5km (Invalid) WHY? is this an echo?

**Comment by amirhaleem** [comment]
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum.

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, Process for managing Helium Improvement Proposals

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

Closing this as invalid but feel free to ask further questions here or in Discord
