### ISSUE TITLE
HIP19: Report or Standardize hotspot DNS naming across all vendors

### ISSUE THREAD

**Issue by waveform06** [helium/HIP#220]
I'm making a suggestion for HIP19 that vendors visibly disclose the format/style of hotspot DNS names - or adhere to a suggested standard. 
As all the different vendors hotspots appear in different naming formats when looking on the routers - I believe some are unique per hotspot and some are the same for every hotspot. 
Some hotspots can be identified by the DNS name and some cant. 
It will help with discord support and many of the forwarding questions if this could be put into user manuals or tech forums.
Or on  https://docs.helium.com/troubleshooting/network-troubleshooting

**Comment by jamiew** [comment]
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

Closing this as `invalid` but feel free to ask further questions here or in Discord
