### ISSUE TITLE
No rewards since 24 hours 

### ISSUE THREAD

**Issue by ronikhalil** [helium/HIP#225]
Hi 
I just started 4 days ago and I the first 3 say I was making 3 hnt a day but since 24 hours I didn’t make any rewards and even all the miner who are near me either didn’t make any rewards 

is this normal and do I need to do any things to fix the issue 

my miner : Straight Ruby Huskie
NewWestminster BC Canada 

![45D93ECF-7BE6-4ABA-AC3D-D40A259C140D](https://user-images.githubusercontent.com/63904767/124052289-00391580-d9d3-11eb-8066-bf255983aa59.png)

**Comment by jamiew** [comment]
This repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

Closing this as `invalid` but feel free to ask further questions here or in Discord
