### ISSUE TITLE
An interesting and effective idea (not just for cheating)

### ISSUE THREAD

**Issue by Cola555** [helium/HIP#240]
I have an interesting and effective proposal here. The mining income of hnt can be distributed according to the population of each city, and the more the population, the more hnt should be distributed in cities. If there are fewer mining machines in a city with a large population, you can set an upper income limit for each mining machine. Those who make virtual positioning (cheating) like to put mining machines in deserted suburbs, forests, fields and mountains. First, the benefits of cheating can be greatly reduced in this way. Because of the decrease in income, cheating is bound to decrease slowly. Secondly, this method will also contribute to the ecological development of helium in the future. Because many applications need to run in big cities with many people. I think this way is very beneficial to the continuous development of helium in the future. Third, this approach is also conducive to helium's faster and wider layout of all cities in the world. Of course, my ideas have just come into being, and there are still many areas to be improved. I hope everyone can correct and improve them.

**Comment by jamiew** [comment]
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

Closing this as `invalid` but feel free to ask further questions here or in Discord
