### ISSUE TITLE
HIP36: Blockheight Chainvar Activation

### ISSUE THREAD

**Issue by jamiew** [helium/HIP#260]
## Info 

- Author(s): [@BFX](http://github.com/Bx64/)
- Start Date: 2021-08-06
- Category: Technical
- Original HIP PR: [257](https://github.com/helium/HIP/pull/257)
- Tracking Issue: not filed yet
- Status: In Discussion
- Discord channel: `#hip-36-blockheight-chainvars` on https://discord.gg/helium

## Rendered view

https://github.com/helium/HIP/blob/master/0036-blockheights-instead-of-time.md

## Summary

At the time of writing, most (if not all) blockchain variables and implementations are activated manually by the Helium team, requiring active intervention from the team and have a time-based activation. The active intervention can, for the greatest part, be avoided by enabling auto-activation of variables at certain blockheights. This has been the standard for most blockchain projects. One example is the bi-yearly halving of HNT rewards agreed to in HIP20 which should be integrated with blockheights rather than be defined by moment in time for its activation - and in the future, hopefully any change of blockchain variables can be defined that way.

**Comment by vincenzospaghetti** [comment]
Hi @Bx64, This HIP has been open for some time without any noticeable action. We are going to move to close this HIP. Please let us know if there is a reason not to.
We will close this by the end of the week (10/28).
