### ISSUE TITLE
Hi helium

### ISSUE THREAD

**Issue by BCTVFoundation1** [helium/HIP#261]
I'm a crypto exchange https://bqex.us I would like to list HNT and be a manufacturer of HNT mining machines please advice for applications steps

**Comment by jamiew** [comment]
This repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

Closing this as `invalid` but feel free to ask further questions here or in Discord
