### ISSUE TITLE
404 on the page of manufacturer application

### ISSUE THREAD

**Issue by jingdracaena** [helium/HIP#266]
the template for manufacturer application under HIP/0019-third-party-manufacturers.md is invalid: https://github.com/helium/HIP/blob/master/0019-third-party-manufacturers/TEMPLATE.md

**Comment by jamiew** [comment]
Thanks for filing the issue. Per #259 these have all moved to a new repository: https://github.com/dewi-alliance/hotspot-manufacturers

This is mentioned in the README and a few other places, but please let me know if there's other places we should correct the links cc @Sophi
