### ISSUE TITLE
Add links for `deployed` HIPs 

### ISSUE THREAD

**Issue by jamiew** [helium/HIP#27]
Currently we have several HIPs which have been merged and deployed to the blockchain, but it'd be good to have the proof in the associated `.md` file. I'm specifically thinking about HIPs 1-4

**Comment by jamiew** [comment]
HIP10 I can track down, but looking for some help tracking down PRs, commits and/or chainvar transactions for the following:

![HIP: Helium Improvement Proposals ](https://user-images.githubusercontent.com/1903/95468474-8c3e7500-094c-11eb-95c7-8f55ad5c1554.png)

**Comment by vincenzospaghetti** [comment]
@jamiew do we still need this open? How do we resolve this?

**Comment by jamiew** [comment]
@vincenzospaghetti arguably if it hasn't happened by now it's not gonna happen. Same as #295 which I'll also close RIP
