### ISSUE TITLE
Helium explorer showing relayed when not

### ISSUE THREAD

**Issue by haze94** [helium/HIP#274]
Today my helium explorer app started showing I'm in relayed mode when my sensecap dashboard shows everything is good and not in relayed mode I noticed my listen ip is missed up again showing Random reading instead of actual ip wasn't there an update for this recently please help

**Comment by jamiew** [comment]
@haze94 this is a repository for blockchain governance, not hotspot issues. Please try the Discord #hotspot-issues channel instead
