### ISSUE TITLE
HIP38: Validator Oracles

### ISSUE THREAD

**Issue by jamiew** [helium/HIP#282]
## Info 

- Author(s): @cvolkernick
- Start Date: 2021-09-06
- Category: Economic, Technical
- Original HIP PR: https://github.com/helium/HIP/pull/272
- Tracking Issue: https://github.com/helium/HIP/issues/282
- Discord channel: `#hip-38-validator-oracles` on https://discord.gg/helium

## Rendered view

https://github.com/helium/HIP/blob/master/0038-validator-oracles.md

# Summary
[summary]: #summary

From Helium Docs:

>HNT converts to Data Credits at a rate pegged to $.00001 , and so the blockchain requires a canonical HNT/$USD price for this conversion. Beginning in June 2020, the Helium blockchain started using a system of decentralized price oracles to supply the $USD to HNT price used for on-chain for burn transactions. (This system is inspired by the Maker Foundation's Oracle usage.)
>
>To find this price, nine oracles (***this number may change in the future***) periodically submit HNT/$USD prices. Once the blockchain has enough new price data, it will calculate a new HNT/$USD price that will remain valid until enough new, valid oracle inputs are submitted, triggering a new price revision.

This HIP proposes not only changing this number, but also expanding the pool of those who are able to make submissions. It proposes empowering any staked validators with the existing `price_oracle_submission` & allowing them to commit price oracle submissions as chain-blessed Oracles.

**Comment by cvolkernick** [comment]
> @cvolkernick would you be willing to quick present & field questions about your HIP on this week's community call? Weds @ noon ET

Sure thing.
