### ISSUE TITLE
I have a two hotspots, in the beginning they are working, after some electric discounting now the first one not working and said "Needs attention".

### ISSUE THREAD

**Issue by naligalalay** [helium/HIP#293]
I have two hotspots; in the beginning, they are working and each other a witness; after some electric discounting, the first one is not working and says: "Needs attention."
Kindly for your advice.

**Comment by jamiew** [comment]
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

Closing this as `invalid` but feel free to ask further questions here or in Discord
