### ISSUE TITLE
Missing HIPs: 3, 8, 9

### ISSUE THREAD

**Issue by maco2035** [helium/HIP#295]
There are several hips that are missing from the master branch of the HIPs. Once taught lost to time, git has saved us once more.

Hip-0008: https://github.com/helium/HIP/blob/c2f3ce61466b003731bb967959ca8b6e7706fca5/0008-lorawan-routing.md
Hip-0009: https://github.com/helium/HIP/blob/7b715a0614d4c529144e1d6c0083ee8b38c05b29/0009-non-helium-hotspots.md

Hip-0003: Is in the master branch, however it is not on the chart.

**Comment by vincenzospaghetti** [comment]
@jamiew to fix :)

**Comment by vincenzospaghetti** [comment]
@jamiew how can we get someone to help us resolve this?

**Comment by jamiew** [comment]
This has been open for over a year without any further fixes so closing as stale

Would be nice for completeness but doesn't seem like it's bothering anyone!
