### ISSUE TITLE
HIP 47: Increase DKG Failure Penalty

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#313]
- Author(s): [@PaulVMo](https://github.com/PaulVMo)
- Start Date: 2021-10-26
- Category: Technical
- Original HIP PR: https://github.com/helium/HIP/pull/306
- Tracking Issue: this
- Status: In Discussion

# Summary
[summary]: #summary

Increase the DKG penalty amount from the current value of 1.0 to 5.0. The DKG penalty is assessed when a validator fails to complete the distributed key generation (DKG) that is required for a consensus group election to complete. A failed election is reattempted 5 blocks later with another set of validators. Repeated election failures are bad for the network and bad for the validator pool. The current DKG failure penalty amount is not significant enough to drive change in behavior for misconfigured and poor performing validators. By tuning the penalty amount in this way, failed validators should be more quickly removed from eligibility for consensus group and hopefully provide greater incentive for operators to improve the performance of their validators.

# Rendered view

https://github.com/helium/HIP/blob/master/0047-increase-dkg-penalty.md

**Comment by jamiew** [comment]
There has been nearly universal support for this proposal and it has passed our general standard for rough consensus. 

On behalf of the DeWi, the HIP Editors team, and the wider Helium community, I am marking this proposal as `approved` and recommending that the coredev team implement the necessary changes as soon as reasonably possible.

**Comment by vincenzospaghetti** [comment]
Hi, @PaulVMo was this approved and implemented? If so, I'm going to close this issue. If I don't receive a response, I will go ahead and close this at the end of the week.

**Comment by PaulVMo** [comment]
Yes, it was approved and implemented
