### ISSUE TITLE
Heltec HT-M2808 Fan speed management

### ISSUE THREAD

**Issue by sajmi** [helium/HIP#317]
Hi guys, 
Would it be possible in the next firmware version to run the fan at a speed adapted to the processor temperature?
at the moment it always starts at the highest speed, which is quite noisy.
Thank you

**Comment by mfalkvidd** [comment]
You’ll probably get better results by contacting Heltec (contact info available at https://heltec-hotspot-docs.readthedocs.io/en/latest/hotspot_faq.html )

**Comment by jamiew** [comment]
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not a support or discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

Closing this as `invalid` but feel free to ask further questions here or in Discord
