### ISSUE TITLE
How to register and join helium family?

### ISSUE THREAD

**Issue by theseusyang** [helium/HIP#321]
Hello helium,
We are coming from China, a startup iot gateway device enterprise, provide an optimized protocol iot device than Lora. has our own communication protocol· its coverage is more wider than lora. power consumption is lower than lora.bandwith is more than lora.
How to register and join helium family?

**Comment by wolfenhawke** [comment]
Should discuss this with Helium Biz Dev.

**Comment by theseusyang** [comment]
Where is Helium Biz Dev?

**Comment by wolfenhawke** [comment]
Have you tried contacting via sales@helium.com or hello@helium.com? Highlight that you want to discuss business development opportunity.

**Comment by theseusyang** [comment]
Last week have send email to hello@helium.com, but no reply.

**Comment by jamiew** [comment]
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not a support or discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

I am closing this as `invalid` but feel free to ask further questions here or in Discord
