### ISSUE TITLE
ABILITY TO PRODUCE HELIUM MINERS///HOW CAN I APPROVE MY UNITS?

### ISSUE THREAD

**Issue by VasilisScarab** [helium/HIP#326]
Dear Community, 
I trust everyone is very well.
My factory has the ability to produce new Helium miners for Worldwide use.
How can I make my units approved for your net???
Your early reply will help me to entry into this fantastic private lan.
Thank you

**Comment by anders462** [comment]
This repo is for HIP's Helium Improvements proposals. If you are interested in becoming a maker please see:
https://github.com/dewi-alliance/hotspot-manufacturers/
https://github.com/helium/HIP/blob/master/0019-third-party-manufacturers.md

Happy Holidays!

**Comment by jamiew** [comment]
@anders462 has it correct, thanks for replying
