### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by jamiew** [helium/HIP#332]
What is this, 2021? 

This will break existing checkouts but I do not think there are many

I don't have permission to do this myself or would just do it <3

**Comment by abhay** [comment]
@jamiew I can certainly do this if we feel strongly about it. It appears to be fairly straight forward. https://github.com/github/renaming#rename-existing

**Comment by jamiew** [comment]
Yes it's quite easy! I would appreciate it, `main` is a much better name and more and more apps now expect that. And switching really only a pain for folks with an existing checkout, of which I don't think we have many

**Comment by abhay** [comment]
![image](https://user-images.githubusercontent.com/75/151449609-4b66175f-6aff-4935-b375-6c46648c1784.png)
it is done.

**Comment by jamiew** [comment]
<3<3 thank you
