### ISSUE TITLE
HIP - Troubleshooting Time Limit of Offline/Disabled Hotspots 

### ISSUE THREAD

**Issue by fantasmathm** [helium/HIP#333]
Hello Helium community, hope this HIP finds everyone well..

I have zero to no knowledge on writing a HIP or even coding so I apologize in advanced.

We have a small community of Helium miner operators in Puerto Rico, that accounts for approximately half of the miners deployed in the island. Now, like in other metropolitan city's, we are running into an issue were too many hotspots are being deployed without a strategy for the betterment of the network or the operators. In Resolution 5, we currently have 169 hotspots above the limit. Where there are +- 130 offline/disabled. I see the same issue in many other high density cities. 

We all believe it is due to all these new companies offering % for people to host hotspots by promising 'plug and earn' schemes without really caring about the network... 

I do not understand how these offline/disabled hotspots affect the network itself, but I do know it is affecting us who believe in this project for the long run. We coordinate installations and work together as a team to expand the network efficiently across the island. In the end this is the 'People's Network'. 

We recommend, if possible, to set a time limit on these offline/disabled hotspots so the hosts can troubleshoot/correct the issues before penalizing them. If they can be removed temporarily from the blockchain, they can allow other miners in the same resolutions to improve their transmit scale drastically.

We are dedicated in growing the network correctly, to incentivize growth of the project. 

Thanks in advance!

**Comment by norbertoperez23** [comment]
This is a good one. Should help out in decongesting many areas with too many offline hotspots. I vote for this.

**Comment by chitulea** [comment]
Nice one i will like to take them out from the hex asap for the good of the remaining ones

**Comment by pellechi1** [comment]
I too agree with this one … a ‘timer’ (possibly measured in consecutive months) should automatically remove the entry from the blockchain. 

In the interim, it would be an education to know ‘why’ the owners took the devices offline … 
Was it early adopters that experienced unrealized gains? 
Was it software/firmware updates that  caused the miner to go offline unpredictably? (In the 2 months the miner in my home has existed, it’s had 3 updates AND each resulted in my router having significant functionality issues requiring complete reboots)

**Comment by BFGNeil** [comment]
Hotspots loose their interactive status after being offline for around 2.5 days, at this stage they do not count for scaling.

https://github.com/helium/HIP/blob/master/0017-hex-density-based-transmit-reward-scaling.md#getting-interactive-and-losing-interactive-status

**Comment by jamiew** [comment]
Thanks Neil for the thoughtful reply

For the future, this repository is for formal Helium Improvement Proposals (HIPs) and is not a support or discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

I am closing this as `invalid` but feel free to ask further questions here or in Discord
