### ISSUE TITLE
Gaming deepers

### ISSUE THREAD

**Issue by legiovi** [helium/HIP#377]
112oGnrbkaDDVB8MkzjwTfNbJvQKPhimYeNPqVZaCfnmC9R9JkUr
14Pyen8NeZh23ZEV9tCuHssmdZ4BkJeT6RoTuRhGqnXxTs7RS4C
11DXVZwcKqUBmyzZkcBb8Bwf9qR82Qgr2drVudDQg8ADEXB47My
14VhT6Jgpov54ZFGvpnKH5yBowWeZj6nhHVXEHCSBsBtHATNhrj
1125Zz3w39Ak6psDDwmaLCGMP7oshr38up37VtXvotDKsc3JKHzn
14Pyen8NeZh23ZEV9tCuHssmdZ4BkJeT6RoTuRhGqnXxTs7RS4C

Deepers witness only between them , this is a common issue that its affecting the entire network.

**Comment by snip** [comment]
I think this is the wrong place to report this.
You should do it here: https://github.com/helium/denylist

**Comment by oosui** [comment]
Some makers themselves are doing this. They changed the forwarder/miner in the witness node to accept only their own witnesses and also changed the RSSI and SNR in their witness nodes.
