### ISSUE TITLE
but he can help me with the problem I have with my miner Bobocat300, he doesn't do anything for many hours, that is 12, , 15.20 h daily https://explorer.helium.com/hotspots/latest mining name. Swif Vini Babger. Romania (Bucharest)

### ISSUE THREAD

**Issue by Crisatian** [helium/HIP#380]
but he can help me with the problem I have with my miner Bobocat300, he doesn't do anything for many hours, that is 12,
, 15.20 h daily https://explorer.helium.com/hotspots/latest mining name. Swif Vini Babger. Romania (Bucharest)

**Comment by jamiew** [comment]
Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not a support or discussion forum. 

If you'd like to write and submit proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

I am closing this as `invalid` but feel free to ask further questions here or in Discord
