### ISSUE TITLE
HIP69 The "Champaign" update  

### ISSUE THREAD

**Issue by Heefi69** [helium/HIP#387]
-Quake server added onto chain after light hotspots are activated 
-add a monthly lotto of 1000 HNT that goes to a hotspot randomly chosen 
-online casino where the community can chill, relax and gamble some HNT.
-create an exclusive "Champaign room" for high earners and OGs 
-Discord user @Heefi gets mod....

**Comment by jamiew** [comment]
i love a good joke but boy are you making work for me

**Comment by Heefi69** [comment]
🥂

**Comment by FrankDaTank3** [comment]
Let's go!

**Comment by StinkendeGilbert** [comment]
Don't forget  special rooms like: the green room, and the banned refugees room bro :)))
