### ISSUE TITLE
help honest miners

### ISSUE THREAD

**Issue by gkmel** [helium/HIP#390]
My location is by the sea and it is high, but because of the 100 km border, I am having problems, I have witnessed 110 km, please detect the scammers, it's not our fault :(

![Ekran Görüntüsü (1)](https://user-images.githubusercontent.com/103924526/163774916-82c428a6-8cae-46a7-b339-6d9e3ec9b0b3.png)
r

**Comment by capjbadger007** [comment]
You will not be rewarded for areas where you can't detect sensor transmissions.

**Comment by gkmel** [comment]
That's the problem, my friend, they should make their distance at least 150 km.

**Comment by waveform06** [comment]
This should be a comment in https://github.com/helium/HIP/issues/389
Not a new Issue

**Comment by Bcagatay53** [comment]
https://github.com/helium/HIP/issues/389

**Comment by Bcagatay53** [comment]
[](https://github.com/helium/HIP/issues/389)

**Comment by Bcagatay53** [comment]
[https://github.com/helium/HIP/issues/389](https://github.com/helium/HIP/issues/389)
