### ISSUE TITLE
HIP 66:Checking whether an IP is from China

### ISSUE THREAD

**Issue by johnson1872022** [helium/HIP#467]
`Checking whether an IP is from China. As most cheaters are located in China, it would make sense to preemptively penalize all hotspots in this country. However, this comes with the obvious downside that all honest miners in China would also be penalized.`

I don't think targeting a country is a good idea.
This goes against the principle of decentralization and makes Helium a centralized project.
`China's cryptocurrency holdings are still the second largest in the world despite policy regulation. Helium doesn't respect the Chinese market, there won't be a big rise in HNT price, and there will even be more falls. Once the Chinese market relaxes regulations on cryptocurrencies in the later stage, can Helium still win the Chinese market? Please don't take Denylist only for the Chinese market.  China does not produce HNT.  No matter how high your output is, what's the point?  HNT will become $1 after a long time.`

**Comment by waveform06** [comment]
FYI, you have opened a new HIP proposal, not an issue or a comment on an existing HIP
Is this intended to be a comment on?
https://github.com/helium/HIP/blob/main/0066-trust-score-and-denylist-convenience.md

**Comment by johnson1872022** [comment]
> FYI, you have opened a new HIP proposal, not an issue or a comment on an existing HIP Is this intended to be a comment on? https://github.com/helium/HIP/blob/main/0066-trust-score-and-denylist-convenience.md

yes

**Comment by vincenzospaghetti** [comment]
Thanks for your comment! Please move this comment @johnson1872022 and we will close this issue, as it is not a new HIP.
