### ISSUE TITLE
HIP 71: Reward Mappers

### ISSUE THREAD

**Issue by jeanmouawad** [helium/HIP#474]
### **Helium Mappers Must be rewarded**
Mappers must receive any sort of reward ( can be data credits (DC) ) for their contribution

1. They are buying Lora devices that are supported by the network which creates traffic on the Network
2. They are using Data Credits even if the first 10 000 are free 
3. They are helping deployers and Helium to check Helium Coverage

**Comment by JFVE** [comment]
I agree with you, there are many mappers who have done thousands and thousands of kilometers, obtaining very important data

**Comment by waveform06** [comment]
You need to write a HIP document not just a suggestion. Start by discussing this in the discord #hip-general channel

**Comment by vincenzospaghetti** [comment]
This is not a HIP. Please make a pull request.
