### ISSUE TITLE
Remove my hotspot from denylist 

### ISSUE THREAD

**Issue by Matef1983** [helium/HIP#520]
Please remove my hotspot from denylist

**Comment by vincenzospaghetti** [comment]
Hi @Matef1983 this request isn't a HIP and should follow the instructions to remove a hotspot from the Denylist. This can be found in a couple of places:
-  <https://github.com/helium/denylist#removal-from-this-list>
- <https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request>

See those resources for support and I'm going to close this ticket.
