### ISSUE TITLE
Denylist Status From 3 Months

### ISSUE THREAD

**Issue by shoaib-mohammad** [helium/HIP#521]
My minor helium is on denylist since 3 months ago,
what to do??

It's name  is (Future Shamrock Cyborg)

Do you have any solution ???

**Comment by Ryan-Goldstein** [comment]
This is not where you should submit denylist removal requests. That needs to be done at Crowdspot: https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request
