### ISSUE TITLE
Please help me remove my hotspotes from deny list please

### ISSUE THREAD

**Issue by Gagi1984** [helium/HIP#524]
Joyful rose dog
Gentle bone goose
Abundant sapphire swift

Gagipakeliani@gmail.com

**Comment by vincenzospaghetti** [comment]
Hi @Gagi1984  this request isn't a HIP and should follow the instructions to remove a hotspot from the Denylist. This can be found in a couple of places:

https://github.com/helium/denylist#removal-from-this-list
https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request
See those resources for support and I'm going to close this ticket.
