### ISSUE TITLE
Please remove me from denylust

### ISSUE THREAD

**Issue by Andjamilan** [helium/HIP#539]
Please remove my Hotspot Uneven Cotton Caterpillar
From denylist its real and I am first bayer from manufactor bobcat.Here is prove.
![Picture 313](https://user-images.githubusercontent.com/122698279/213832247-e7824e2d-fedc-47f9-8d49-ab8fa7838b8a.jpg)
![Picture 313](https://user-images.githubusercontent.com/122698279/213832283-b761a971-7497-47db-ad8d-c9c6d60da8ea.jpg)
Forwarded message ----------
From: bobcatminer <[customer@bobcatminer.com](mailto:customer@bobcatminer.com)>
Date: Wednesday, August 25, 2021
Subject: Order 1238142 - Payment Received & Order Confirmed
To: [nikolina94@gmail.conormal; font-
![Hvatanje od ecrans_20230121-025632](https://user-images.githubusercontent.com/122698279/213835967-73562b5f-a855-444d-967a-19a2155e418c.png)
e; w

ORDER 1238142Congrats Milan,Your payment has been received and your order has been confirmed- now leave the rest to us.Expect your order to ship within 12-20 weeks. We’ll send you a shipping confirmation with your tracking number as soon as the order goes out.Thank you for your support.CONNECT WITH USSupport: customer@bobcatminer.comDOWNLOAD DATASHEETSVisit Download Center on the bottom of our websiteMORE FAQ | ORDER 1238142 | ORDER 1238142 |   | ORDER 1238142 | Congrats Milan,Your payment has been received and your order has been confirmed- now leave the rest to us.Expect your order to ship within 12-20 weeks. We’ll send you a shipping confirmation with your tracking number as soon as the order goes out.Thank you for your support.CONNECT WITH USSupport: customer@bobcatminer.comDOWNLOAD DATASHEETSVisit Download Center on the bottom of our websiteMORE FAQ | Congrats Milan,Your payment has been received and your order has been confirmed- now leave the rest to us.Expect your order to ship within 12-20 weeks. We’ll send you a shipping confirmation with your tracking number as soon as the order goes out.Thank you for your support.CONNECT WITH USSupport: customer@bobcatminer.comDOWNLOAD DATASHEETSVisit Download Center on the bottom of our websiteMORE FAQ
-- | -- | -- | -- | -- | -- | --
ORDER 1238142 | ORDER 1238142 |   | ORDER 1238142
ORDER 1238142 |   | ORDER 1238142
  | ORDER 1238142
Congrats Milan,Your payment has been received and your order has been confirmed- now leave the rest to us.Expect your order to ship within 12-20 weeks. We’ll send you a shipping confirmation with your tracking number as soon as the order goes out.Thank you for your support.CONNECT WITH USSupport: customer@bobcatminer.comDOWNLOAD DATASHEETSVisit Download Center on the bottom of our websiteMORE FAQ | Congrats Milan,Your payment has been received and your order has been confirmed- now leave the rest to us.Expect your order to ship within 12-20 weeks. We’ll send you a shipping confirmation with your tracking number as soon as the order goes out.Thank you for your support.CONNECT WITH USSupport: customer@bobcatminer.comDOWNLOAD DATASHEETSVisit Download Center on the bottom of our websiteMORE FAQ
Congrats Milan,Your payment has been received and your order has been confirmed- now leave the rest to us.Expect your order to ship within 12-20 weeks. We’ll send you a shipping confirmation with your tracking number as soon as the order goes out.Thank you for your support.CONNECT WITH USSupport: customer@bobcatminer.comDOWNLOAD DATASHEETSVisit Download Center on the bottom of our websiteMORE FAQ

</div>Received & Order Confirmed
To: [nikolina94@gmail.com](mailto:nikolina94@gmail.com)

bobcatminer	ORDER 1238142

Congrats Milan,

Your payment has been received and your order has been confirmed- now leave the rest to us.

Expect your order to ship within 12-20 weeks. We’ll send you a shipping confirmation with your tracking number as soon as the order goes out.

Thank you for your support.

CONNECT WITH US

Support: customer@bobcatminer.com

DOWNLOAD DATASHEETS

Visit Download Center on the bottom of our [website](https://www.bobcatminer.com/)

MORE FAQ

**Comment by samgutentag** [comment]
Hello, this is not the correct location for this information. Please submit a removal request on [www.crowdspot.io](https://www.crowdspot.io)

**Comment by Andjamilan** [comment]
It is corect location because you didnt setup corect location.It Cant pair with helium wollet.😠

**Comment by madninja** [comment]
Please try again. If you need assistance ask on Discord in the crowdspot channel
