### ISSUE TITLE
HIP 82: Add Helium Mobile as a Service Provider to the Helium Mobile subDAO

### ISSUE THREAD

**Issue by vincenzospaghetti** [helium/HIP#628]
# HIP 82: Add Helium Mobile as a Service Provider to the Helium Mobile subDAO

- Author(s): [@zer0tweets](https://github.com/zer0tweets), [@meowshka](https://github.com/meowshka) (Nova Labs, Inc.)
- Start Date: 2023-03-15
- Category: economic, technical
- Original HIP PR: #581
- Tracking Issue: #628

## Summary

This HIP proposes to introduce Helium Mobile as a Service Provider (as defined in [HIP53](https://github.com/helium/HIP/blob/main/0053-mobile-dao.md#economics-overview)) on the Mobile Network. The main goal is to bring usage to the Network and pave the way for other Service Providers to join. The HIP describes integration with Helium Mobile Network, anti-gaming mechanism, and overall impact on the Network.

## Motivation

The Community has gone a long way in building Helium Mobile Network and now is the perfect time to bring usage and utility to it.

As a Service Provider member of the Helium Mobile subDAO, Helium Mobile will actively offload its subscriber traffic into the Helium Mobile Network.  The launch of the Helium Mobile carrier will help pave the path for other Service Providers coming to the Network by ironing out any undiscovered issues and creating a smooth onboarding process.  In addition, the increased traffic on the network as a result of the launch will have a commensurate increase in HNT burn and data rewards for Hotspot operators.

## Rendered View
https://github.com/helium/HIP/blob/main/0082-helium-mobile-service-provider.md

**Comment by vincenzospaghetti** [comment]
Note: #636 was merged into this file and adds info about one year grace period to allow for zero-rated traffic

**Comment by waveform06** [comment]
HIP 82 was approved by the community on 16th June 2023 with a passing rate of 99.9%
https://realms.heliumvote.com/dao/mobile/proposal/3u2DUcZ2GMRviU5Ycy827urBtovutUiGrt3jqJHQek3w
