### ISSUE TITLE
What to do with forfeited HNT? 

### ISSUE THREAD

**Issue by Tony12times** [helium/HIP#669]
I like this HIP but think it needs to go further. 

1. Where does the HNT go that is forfeited by people who submit denied requests?  I propose it goes to a Subdao with the funds set aside for compensation of those who have waited moths for a review already. Should a removal request be validated it should be easy to see the date the hotpot was put on the deny list and how many days have passed to a successful review. a compensation could be fixed at 0.05 HNT a day for example. This can be in conjunction with the HIP entitled : Hold_Rewards_for_Denylist_Hotspots.  This is a show of good faith in Innocent hotspot owners and restores trust in the network. 

submitted.

_Originally posted by @Screwtape7 in https://github.com/helium/HIP/issues/662#issuecomment-1556007256_
            

This issue has been questioned in PR 551 and referenced in this PR under "Unresolved Questions "

**Comment by vincenzospaghetti** [comment]
@Tony12times - I think you put this comment in the wrong place. Make sure it's on your PR. This was opened as an Issue ticket. I am closing it.

**Comment by Tony12times** [comment]
@vincenzospaghetti yes.  I made as an accident and asked for help right after I realized it.
