### ISSUE TITLE
HIP 87: Proportional Service Provider Rewards

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#704]
# HIP 87: Proportional Service Provider Rewards
- Author(s): [@KeithRettig](https://github.com/KeithRettig), [@zer0tweets](https://github.com/zer0tweets), [@meowshka](https://github.com/meowshka)
- Start Date: 2023-05-15
- Category: Economic, Technical
- Original HIP PR: [#699](https://github.com/helium/HIP/pull/699)
- Tracking Issue: [#704](https://github.com/helium/HIP/issues/704)
- Voting Requirements: veMOBILE Holders

## Summary
This HIP proposes to make specific how Service Providers are eligible for rewards from the HIP53-specified Service Provider MOBILE Reward bucket.  The proposal suggests a usage-based approach to calculate rewards for Service Providers based on the amount of Data Credits burned.  Service Providers would be rewarded in MOBILE tokens at a 1:1 ratio for the burned Data Credits with proportional distribution if the total exceeds the reward bucket value.

## Motivation
The primary motivation is clarify how Service Provider Rewards are calculated.  There is also a motivation to prevent a scenario in which a Service Provider is rewarded the full MOBILE reward bucket while burning little to no Data Credits.  The content of this HIP was originally written within HIP82.  However, since the concept applies to all Service Providers in the Helium 5G Network and not to the specific Service Provider of HIP82, it is more appropriate to have this as its own HIP.

## Rendered View:
https://github.com/helium/HIP/blob/main/0087-proportional-service-provider-rewards.md

**Comment by waveform06** [comment]
@hiptron Realms voting text is here
https://gist.github.com/waveform06/f76f4741869000607db7f3dab6e15628

**Comment by waveform06** [comment]
HIP 87 is up for voting on
https://realms.heliumvote.com/dao/mobile/proposal/DtMtA61XvnNWAPb3rr9isaPPHopUQCHFhAu5QJmaNy1k

**Comment by waveform06** [comment]
This HIP is now deployed

**Comment by waveform06** [comment]
Repealed by [HIP 148](https://github.com/helium/HIP/issues/1187)
