### ISSUE TITLE
HIP 89: MOBILE Network Onboarding Fees

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#714]
# HIP 89: MOBILE Network Onboarding Fees 
- Authors: [Andy Zyvoloski](https://github.com/heatedlime), [Keith Rettig](https://github.com/keithrettig), [Max Gold](https://github.com/MaxGold91)
- Start Date: 6/14/2023
- Category: Technical & Economic
- Original HIP PR: [#701](https://github.com/helium/HIP/pull/701)
- Tracking Issue: [#714](https://github.com/helium/HIP/issues/714)
- Voting Requirements: veMOBILE

## Summary
This HIP requests that The Helium Foundation correct the MOBILE Onboarding Fee from 0 USD to 40 USD as soon as possible so that the MOBILE Onboarding Fee will be in compliance with HIP 53. 

## Motivation
Current MOBILE Hotspots, such as the FreedomFi Gateway and the Bobcat 500, are both omni-protocol Hotspots; that is, they contain both IOT and MOBILE network capabilities.  HIP 53 ('Economics Overview' section) dictates that all Hotspots must pay an Onboarding Fee of 40 USD and a Location Assert Fee of 10 USD.  [Helium Maker Ethics Documentation](https://docs.helium.com/hotspot-makers/maker-ethics/)  Section 9 indicates that Approved Hotspot Makers are responsible for funding the onboarding server for their Hotspots.

At the time of onboarding these Hotspots, there was no MOBILE subDAO which to designate the MOBILE subDAO's 40 USD Onboarding Fee.  As such, all MOBILE Hotspots were only onboarded to the IOT network with its associated Onboarding Fee of 40 USD and Location Assert Fee of 10 USD.  At the time of the Solana migration in April of 2023, these Hotspots continued to be onboarded to the MOBILE network with an Onboarding Fee of 0 USD instead of 40 USD, as the migration kept feature parity with the old chain.  The discrepancy continues to this day.  As a result, 0 USD in Onboarding Fees have been burned towards the MOBILE subDAO's $A$ Factor, which creates a negative impact in the $A$ Score of the DAO Utility Score established in HIP 51.

## Rendered View:
https://github.com/helium/HIP/blob/main/0089-mobile-network-onboard-fees.md

**Comment by hiptron** [comment]
Updated summary to reflect changes.

**Comment by waveform06** [comment]
HIP 89 was approved by the community on 8th June 2023 with a passing rate of 96.8%
https://realms.heliumvote.com/dao/mobile/proposal/8AZepByGXEejTYwy3mLKA57k19w27uukc9QUhJHFVYwj
