### ISSUE TITLE
On deny list without reason

### ISSUE THREAD

**Issue by 90knele90** [helium/HIP#774]
Please I plugged in my minner and it worked perfectly a couple of days back started to fall lots per day and today I see that I'm on the deny list.  Please help I have a picture of the setup from the first day it's the same. Nick is Plain Bronze Dog. For any additional info i m avalable.

**Comment by Ryan-Goldstein** [comment]
This is not the right place for that request - please join the Helium Discord at https://discord.gg/helium and go to the #crowdspot-denylist channel there, and read the pinned messages.

**Comment by 90knele90** [comment]
I been on Discord and nobody knows the answer to tell me why I am on the deny list. I want someone to tell me what I did wrong and if I made mistakes to correct them. I have a machine that does not work and I lose money.
