### ISSUE TITLE
HIP 95: Self-Onboard Hotspots After Maker Exit

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#775]
# HIP 95: Self-Onboard Hotspots After Maker Exit

- Author(s): [@shawaj](https://github.com/shawaj), [@Sophi](https://github.com/sophi), [@ke6jjj](https://github.com/ke6jjj), [@ChewingGlass](https://github.com/ChewingGlass)
- Start Date: 2023-07-15
- Category: Economic, Technical
- Original HIP PR: [#744](https://github.com/helium/HIP/pull/744)
- Tracking Issue: [#775](https://github.com/helium/HIP/issues/775)
- Vote Requirements: veHNT holders

## Summary

There are three types of hotspots available when manufacturers leave the network (regardless of whether updates and support are taken over by another business):

1. Onboarded hotspots that have had location asserted.
2. Onboarded hotspots that have not had their locations asserted.
3. Un-onboarded hotspots in customer or reseller possession.

The onboarding fee is collected as a part of the hotspot price by the manufacturer, but the onboarding and assert fees are not collected from the maker-wallet when the hotspot is shipped, but are delayed and collected when the hotspot is onboarded by the user. This allows for the manufacturer to sell a hotspot and not have DC available to pay for the onboarding.

This HIP proposes a mechanism to improve the onboarding experience for hotspot users whose makers have left the network either through bankruptcy, business closure, failure for compliance, involuntary loss of staking key, the former business being taken over by a new business owner or any other reason. Currently, if a maker leaves the network and they have run out of onboarding DC credits, users are left with only cumbersome or risky ways to onboard their devices to the network. This proposal seeks to change this in a way that lets users onboard their devices in a self-service manner if their hotspot maker has left the ecosystem.

This proposal excludes data-only hotspots as their owners can already onboard using their own wallet.

## Rendered View

https://github.com/helium/HIP/blob/main/0095-self-onboard-hotspots-after-maker-exit.md

**Comment by waveform06** [comment]
@shawaj @Sophi @ke6jjj Now that users can self onboard and select for the Maker or their own wallet to pay for the onboard is there any need for this HIP to go forward?
Other than maybe something for the processes for the MCC or Foundation to follow to move a maker between the status of Good/Suspend Onboarding/Flagging as Defunct/Maker wallet closed.
