### ISSUE TITLE
On deny list without reason

### ISSUE THREAD

**Issue by 90knele90** [helium/HIP#778]
Please I plugged in my minner and it worked perfectly a couple of days back started to fall lots per day and today I see that I'm on the deny list. Please help I have a picture of the setup from the first day it's the same. Nick is Plain Bronze Dog. For any additional info i m available. I been on Discord and nobody knows the answer to tell me why I am on the deny list. I want someone to tell me what I did wrong and if I made mistakes to correct them. I have a machine that does not work and I lose money.

**Comment by waveform06** [comment]
This repository is for Improvement Proposals. This issue will be closed if you do not close it yourself 
Help on the denylist is available in the #crowdspot-denylist channel on the Helium Discord. Please read the pinned messages there first.

**Comment by 90knele90** [comment]
I read msg there and i dont have answer on my problem. No one have to say you on deny list because that and that. 3 month work and now deny WHY? i want to my machine work not to sit and watch.

**Comment by abhay** [comment]
Closing this again like #774. Please use correct channels.
