### ISSUE TITLE
HIP 100: Deploy EU868 Region Plan to the Majority of Africa

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#809]
# HIP 100: Deploy EU868 Region Plan to the Majority of Africa

* Author: [Adrian Clint](https://github.com/waveform06) and [Helium Foundation](https://github.com/dewi-alliance) 
* Start Date: 2023-09-22
* Category: Technical
* Original HIP PR: [#789](https://github.com/helium/HIP/pull/789)
* Tracking Issue: [#809](https://github.com/helium/HIP/issues/809)
* Vote Requirements: veIOT Holders

## Summary

This HIP recommends that the community provisionally sets the currently unspecified and EU433 countries in the Africa region to the EU868 frequency plan. This change would match guidance from local regulatory authorities like the Africa Telecoms Union (ATU) and local deployers. The LoRa Alliance does not currently specify regional parameters for all of these countries, or has EU433 as an only/primary frequency plan.

As a summary, this HIP proposes:

* All Africa region countries with an “Unknown” LoRaWAN regional frequency plan are set to EU868 per ETSI [EN300.220-2].
* All Africa region countries set to EU433 as the default LoRaWAN regional frequency parameter are set to EU868 on the Helium network.
* All Africa region countries with EU433 or an 800MHz based LoRaWAN regional frequency parameter are set to EU868 on the Helium network.
* The network, through the Helium Foundation and other participants, communicate with Telecom Regulatory Authorities in these countries and confirm Helium provisionally complies with the EU868 regional parameter recommendation from the Africa Telecoms Union.
* The network, through the Helium Foundation and other participants, present the approach to the LoRa Alliance Regulations and Regional Parameters Working Group.

# Rendered View

https://github.com/helium/HIP/blob/main/0100-deploy-eu868-region-plan-to-the-majority-of-africa.md

**Comment by waveform06** [comment]
HIP 100 was approved by the community on 22nd December 2023 with a passing rate of 99.93%
https://realms.heliumvote.com/dao/iot/proposal/99ca9Adku8Zk151vGiySEPcGJxdd8V2wAQkGFK4PcE54
