### ISSUE TITLE
HIP 22: HIP Process v2

### ISSUE THREAD

**Issue by Senterium** [helium/HIP#81]
Discussion of a rewritten HIP process

**Comment by Senterium** [comment]
Seeking feedback and to build off of and add to the HIP.

HIP contains 3 major criteria:

1) incentives for HIP generation
2) quality control
3)

**Comment by jamiew** [comment]
Thanks for the submission. Will review in detail and provide some initial feedback later today.

**Comment by jamiew** [comment]
Oh, sorry, I thought this was the PR. The issues are only used once the PR has been merged in. I'll copy over your description to your PR so people can see this alongside the actual proposal.
