### ISSUE TITLE
HIP 108: Mobile Hotspot Suspension Framework

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#887]
# HIP 108: Mobile Hotspot Suspension Framework

- Author(s): [@zer0tweets](https://github.com/zer0tweets)
- Start Date: 2024-01-27
- Category: Meta, Governance
- Original HIP PR: [#886](https://github.com/helium/HIP/pull/886)
- Tracking Issue: [#887](https://github.com/helium/HIP/issues/887)
- Vote Requirements: veMOBILE Holders

## Summary

This proposal outlines the duties and guidelines for MOBILE hotspot vendors (CBRS and Wi-Fi) as it relates to suspending hotspots engaging in counterproductive and/or malicious activity on the MOBILE network. 

## Rendered Text

https://github.com/helium/HIP/blob/main/0108-mobile-hotspot-suspension-framework.md

**Comment by densone** [comment]
@zer0tweets  it might be worth including know VPN ip addresses. For instance users in China might try to fake the CPI location via VPN backhaul ..
