### ISSUE TITLE
HIP 110: Proxy Voting

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#928]
# HIP 110: Proxy Voting

- Author(s): [Abhay Kumar](https://github.com/abhay) and [Noah Prince](https://github.com/ChewingGlass)
- Start Date: 2024-03-01
- Category: Governance
- Original HIP PR: [#925](https://github.com/helium/HIP/pull/925)
- Tracking Issue: [#928](https://github.com/helium/HIP/issues/928)
- Vote Requirements: veHNT Holders, veIOT Holders, and veMOBILE Holders

---

# Summary

This proposal formalizes the concept of Proxy Voters in [Helium Governance](https://heliumvote.com). Proxy voting is a method of governance wherein a participant may assign their vote, potentially for a limited period of time, to another participant. In Helium Governance, we propose that a voting wallet with veToken power may assign their voting power, for a fixed period of time, to another voting wallet.

One can imagine a situation where a participant may not have the ability or time to properly research all Helium Improvement Proposals and directly vote using their vote power. There are also situations where participants are unable to directly vote, for a variety of reasons, but are able to assign their rights to another party. In either of these cases, we propose that participants can assign their voting power to a wallet held by a participant whom they trust without transferring control of the underlying assets.

Additionally, we propose that this proxy assignment be recursive, meaning that this assignment can then be assigned to another wallet. This allows voting power to flow to the most active representatives.

We also propose that this assignment can be revoked or reassigned at any time allowing the participant to both change their vote for a particular position or entirely reassign their vote power to a new voting proxy wallet. This provides an important balance that allows a voter to retain control at all times.

Finally, we propose that proxy voting in Helium’s ecosystem is broken into seasons that reset every August 1st, aligned with the anniversary of the network. This will ensure that assigned proxies do not get stale.

It is worth noting that the concept of vote assignment already exists in [Realms](https://realms.today) on Solana but as we move to using Modular Governance, we believe that the protocol needs to explicitly formalize this feature. As part of formalizing this feature, the authors would like to create a curated registry of well known Proxies. This will allow people to fully research proxies before they assign voting power. The authors believe that the discovery aspect of voting proxies is important, otherwise it will have limited effectiveness.

**Disclosure**: This HIP is a formal proposal authored by the [Helium Foundation](https://helium.foundation). Employees listed as authors are acting in their official capacity as representatives of the Foundation. All proposals contained within reflect solely the recommendations of the Foundation and not those of any individual author(s).

**Note**: This proposal will likely need to voted on by each separate governance group. Specifically, if it's brought to a vote, a separate vote will be held of veHNT, veIOT, and veMOBILE holders.

## Rendered View

https://github.com/helium/HIP/blob/main/0110-proxy-voting.md

**Comment by waveform06** [comment]
HIP 110 (IOT) was approved by the community on 24th April 2024 with a passing rate of 91.71%
https://heliumvote.com/iot/proposals/4LT2pgAzsUBrVpC2a8xqwBh5Qn78ZjPfCmfbgnZJWwQi

HIP 110 (MOBILE) was approved by the community on 24th April 2024 with a passing rate of 93.30%
https://heliumvote.com/mobile/proposals/4QWyyAErD5axospNVLvyQXA19CuKSpr9JLHGiwjJ7NxE

HIP 110 (HNT) was passed by the community on 24th April 2024 with a passing rate of 93.30%, but failed to gain enough votes to comply with the minimum quorum to be fully approved
https://heliumvote.com/hnt/proposals/DGT2GYTk4Lc5oRRZnBVFRaLE4kCfLAADQYS5979jmshf
HIP 110 (HNT) was put to revote on 11th May 2024 and approved as it met the quorum requirement and passed with 92.28% of the vote.
https://heliumvote.com/hnt/proposals/5JX2WhqeRscZw4u5qWDcA2epqX2fVK9PbRiooUZLPza
