### ISSUE TITLE
HIP 103: Urbanization data is 5 years old and won't be updated until 2030

### ISSUE THREAD

**Issue by industrock** [helium/HIP#940]
Deployments in urban areas that were constructed after the 2020 census are not fully rewarded. Please include a way to manually add urban areas that aren't automatically pulled in from the census data.

**Comment by heatedlime** [comment]
There won’t be a way to add urban areas. If there’s points of interest in un-urban areas with foot fall, they will get max rewards once footfall oracle is released. 

This HIP doesn’t want to incentivize deployments outside of areas with high footfall.
