### ISSUE TITLE
HIP 116: LoRaWAN Device Address Price Adjustment

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#959]
# HIP 116: OUI Additional Address Space Reshuffle

- Author(s): [@ccall48](https://github.com/ccall48), [@nowiresfil](https://github.com/nowiresfil)
- Start Date: 2024-03-25
- Category: Technical
- Original HIP PR: [#948](https://github.com/helium/HIP/pull/948)
- Tracking Issue: [#959](https://github.com/helium/HIP/issues/959)
- Vote Requirements: veIOT Holders

---

## Summary
With the initial purchase of an OUI it is mandatory for a LNS operator to either supply an Lora Alliance NetID or purchase
a minimum device address block from the Helium Foundation for $100 per address, with a minimum purchase of 8 for ($800 USD).

[Helium OUI Documentation](https://docs.helium.com/iot/run-an-lns/buy-an-oui)

This proposal is to increase the amount of address space from 8 to 128 for the same minimum one time purchase price.

## Rendered View

https://github.com/helium/HIP/blob/main/0116-lorawan-device-address-price-adjustment.md

**Comment by waveform06** [comment]
HIP 116 was approved by the community on 14th May 2024 with a passing rate of 90.16%
https://heliumvote.com/iot/proposals/3vvLJ3tkuZKpq4dYYNDNbCED3qDzu9BdZYCsN5HoEV1u
